models.py
from flask_sqlalchemy import SQLAlchemy
from datetime import datetime
from sqlalchemy import func
from flask import  url_for
from werkzeug.datastructures import ImmutableMultiDict

db = SQLAlchemy()

class Category(db.Model):
    __tablename__='categories'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)
    description = db.Column(db.String, unique=True)
    books = db.relationship('Books' , backref="category_name", lazy= True)

    def __str__(self):
        return f"{self.name}"

    @classmethod
    def get_all_categories(cls):
        return cls.query.all()

    @classmethod
    def get_category_by_id(cls, id):
        return cls.query.get_or_404(id)

    @classmethod
    def save_category(cls, request_data):
        # Convert ImmutableMultiDict to dict if necessary
        if isinstance(request_data, ImmutableMultiDict):
            request_data = request_data.to_dict()

        # Remove csrf_token from request_data if present
        if 'csrf_token' in request_data:
            del request_data['csrf_token']

        category = cls(**request_data)
        db.session.add(category)
        db.session.commit()
        return category

class Books(db.Model):
    __tablename__ = "books"
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String)
    image = db.Column(db.String, nullable=True)
    price = db.Column(db.Integer)
    no_of_pages = db.Column(db.Integer)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=func.now())
    category_id = db.Column(db.Integer, db.ForeignKey('categories.id'), nullable=True)


    def __str__(self):
        return f"{self.title}"


    @classmethod
    def get_all_objects(cls):
        return cls.query.all()

    @classmethod
    def get_book_by_id(cls,id):
        return cls.query.get_or_404(id)



    @property
    def image_url(self):
        return url_for('static',filename=f'books/images/{self.image}')


    @property
    def show_url(self):
        return url_for("books.books_show",id=self.id)

    @classmethod
    def save_book(cls, request_data):
        # Convert ImmutableMultiDict to dict if necessary
        if isinstance(request_data, ImmutableMultiDict):
            request_data = request_data.to_dict()

        # Remove csrf_token from request_data if present
        if 'csrf_token' in request_data:
            del request_data['csrf_token']

        book = cls(**request_data)
        db.session.add(book)
        db.session.commit()
        return book




    @staticmethod
    def update_book(book, form_data):
        try:
            # Update the book's information
            book.title = form_data.get('title')
            book.image = form_data.get('image')
            book.price = form_data.get('price')
            book.no_of_pages = form_data.get('no_of_pages')
            db.session.commit()
            return True
        except KeyError:
            db.session.rollback()  # Rollback changes in case of error
            return False


    @classmethod
    def delete_book(cls, id):
         # Get the book object from the database
         book = Books.get_book_by_id(id)
          # Delete the book from the database
         db.session.delete(book)
         db.session.commit()
         return True

books/forms.py
from flask_wtf import FlaskForm
from wtforms import  StringField,IntegerField
from wtforms.validators import DataRequired
from wtforms_sqlalchemy.fields import QuerySelectField
from app.models import Category

class BookForm(FlaskForm):
    title = StringField('Title' , validators=[DataRequired()])
    image = StringField('Image' )
    price = IntegerField('Price' , validators=[DataRequired()])
    no_of_pages = IntegerField('No of pages' , validators=[DataRequired()])
    category_id = QuerySelectField("Category" , query_factory=lambda:Category.get_all_categories())

categories/forms.py
from flask_wtf import FlaskForm
from wtforms import  StringField
from wtforms.validators import DataRequired


class CategoryForm(FlaskForm):
    name = StringField('name' , validators=[DataRequired()])
    description = StringField('description')

__init__.py
from flask import Flask
from app.config import config_options as AppConfig
from app.models import db
from flask_migrate import Migrate
from flask_restful import  Api

def create_app(config_name="prd"):
    app = Flask(__name__)
    current_config = AppConfig[config_name]
    print(current_config)
    app.config['SQLALCHEMY_DATABASE_URI'] =current_config.SQLALCHEMY_DATABASE_URI
    app.config.from_object(current_config)
    db.init_app(app)
    migrate = Migrate(app, db ,render_as_batch=True)

    from app.books import book_blueprint
    app.register_blueprint(book_blueprint)

    from app.categories import  category_blueprint
    app.register_blueprint(category_blueprint)


    api= Api(app)
    from app.books.api_views import BookList , bookResource
    api.add_resource(BookList, '/api/books')
    api.add_resource(bookResource , '/api/books/<int:bk_id>')

    return app

books/__init__.py
from flask import Blueprint

#books= Blueprint('')

book_blueprint= Blueprint("books",__name__,url_prefix="/books")

from app.books import  views
from app.books import api_views

books/views.py
from flask import render_template ,request,redirect,url_for, make_response
from app.models import Books ,db
from app.books import book_blueprint
from app.books.forms import BookForm


@book_blueprint.route('',endpoint='books_index')
def books_index():
    books=Books.get_all_objects()
    return render_template("books/index.html",books=books)


@book_blueprint.route("/<int:id>" , endpoint="books_show")
def book_show(id):
    book= Books.get_book_by_id(id)
    return render_template("books/details.html" , book=book )


@book_blueprint.route("/create" ,methods=['GET','POST'] ,endpoint="create")
def create_book():
    if request.method == 'POST':
        book=Books.save_book(request.form)
        #return redirect(url_for('books.books_index'))
        return redirect(book.show_url)
    return render_template("books/create.html")


@book_blueprint.route("/delete_book/<int:id>" , methods=['POST'])
def delete_book(id):
    # Get the book object from the database
    book = Books.get_book_by_id(id)
    # Delete the book from the database
    db.session.delete(book)
    db.session.commit()
    return redirect(url_for('books.books_index'))


@book_blueprint.route('/update_book/<int:id>', methods=['GET', 'POST'], endpoint="book_update")
def update_book(id):
    # Get the book object from the database
    book = Books.get_book_by_id(id)

    if request.method == 'POST':
        if Books.update_book(book, request.form):
            return redirect(url_for('books.books_index'))
        else:
            return redirect(request.url)

    # Render the template with the book data
    return render_template("books/update.html", book=book)


@book_blueprint.route("/createform", methods=['GET', 'POST'], endpoint='createform')
def create_book_viaform():
    form = BookForm(request.form)
    if request.method == 'POST' and form.validate():
        book_data = request.form.to_dict()  # Convert ImmutableMultiDict to dict
        if 'csrf_token' in book_data:
            del book_data['csrf_token']  # Exclude csrf_token from the data
        book = Books.save_book(book_data)
        return redirect(book.show_url)

    return render_template("books/createform.html", form=form)









@book_blueprint.errorhandler(404)
def get_404(error):
    return render_template("error404.html")

categories/__init__.py
from flask import Blueprint
category_blueprint=Blueprint("categories",__name__,url_prefix="/categories")

from app.categories import  views

categories/views.py
from flask import render_template
from app.categories import category_blueprint
from app.models import Category
from app.categories.forms import CategoryForm
from flask import request ,redirect ,url_for

@category_blueprint.route('/home' , methods=['GET'], endpoint='home')
def category_home():
    return "<h1>welcome to category home</h2>"

@category_blueprint.route('/', methods=['GET'] ,endpoint='index')
def category_index():
    categories= Category.get_all_categories()
    return render_template('categories/index.html', categories=categories)



@category_blueprint.route("/createcategory", methods=['GET', 'POST'], endpoint='createcategory')
def create_category_viaform():
    form =CategoryForm(request.form)
    if request.method == 'POST' and form.validate():
        category_data = request.form.to_dict()  # Convert ImmutableMultiDict to dict
        if 'csrf_token' in category_data:
            del category_data['csrf_token']  # Exclude csrf_token from the data
        book = Category.save_category(category_data)
        return redirect(url_for('categories.index'))

    return render_template("categories/createcategory.html", form=form)

templates/books/create.html
{% extends 'layouts/base.html' %}

{% block content %}
<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow-lg">
                <div class="card-header bg-dark text-white">
                    <h1 class="text-center">Add New Book</h1>
                </div>
                <div class="card-body">
                    <form action="{{ url_for('books.create') }}" method="POST">
                        <div class="mb-3">
                            <label for="title" class="form-label">Title</label>
                            <input type="text" id="title" name="title" class="form-control" required>
                        </div>

                        <div class="mb-3">
                            <label for="image" class="form-label">Image </label>
                            <input type="text" id="image" name="image" class="form-control" required>
                        </div>

                        <div class="mb-3">
                            <label for="price" class="form-label">Price</label>
                            <input type="number" id="price" name="price" class="form-control" required>
                        </div>

                        <div class="mb-3">
                            <label for="no_of_pages" class="form-label">Number of Pages</label>
                            <input type="number" id="no_of_pages" name="no_of_pages" class="form-control" required>
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-success">Submit</button>
                               <a href="{{ url_for('books.books_index') }}" class="btn btn-danger">Cancel</a>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/books/createform.html
{% extends 'layouts/base.html' %}
{% import 'macros_.html' as mymacro %}
{% block content %}
<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow-lg">
                <div class="card-header bg-dark text-white">
                    <h1 class="text-center">Add New Book</h1>
                </div>
                <div class="card-body">
                    <form action="{{ url_for('books.create') }}" method="POST">
                        {{ form.csrf_token }}
                         {{mymacro.render_field(form.title)}}
                         {{mymacro.render_field(form.image)}}
                         {{mymacro.render_field(form.price)}}
                         {{mymacro.render_field(form.no_of_pages)}}
                         {{mymacro.render_field(form.category_id)}}
                        <div class="text-center">
                            <button type="submit" class="btn btn-success">Submit</button>
                               <a href="{{ url_for('books.books_index') }}" class="btn btn-danger">Cancel</a>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/books/details.html
{% extends 'layouts/base.html' %}
{% import 'macros_.html' as mymacro %}
{% block content %}
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-8">
            <div class="card shadow">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-5">
                            <img src="{{ book.image_url }}"
                                class="img-fluid rounded" alt="{{ book.title }}">
                        </div>
                        <div class="col-md-7">
                            <h1 class="card-title">{{ book.title }} BOOK</h1>
                            <div class="card-text">
                                <p><strong>Price:</strong> ${{ book.price }}</p>
                                <p><strong>No. of Pages:</strong> {{ book.no_of_pages }}</p>
                                <p><strong>Created_at:</strong> {{ book.created_at }}</p>
                                <p><strong>Updated_at:</strong> {{ book.updated_at }}</p>
                            </div>

                           <h4 style="color:blue;"> Books in this Category : </h4>

          {{mymacro.listobjects(book.category_name.books)}}

                            <hr>
                            <div class="text-center">
                                <a href="#" class="btn btn-primary btn-lg">Buy Now</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/books/index.html
{% extends 'layouts/base.html' %}

{% block content %}
<div class="container">
    <h1 class="text-center mb-4" style="color: brown; font-size: 28px; font-weight: bold; text-transform: uppercase;">
        Books Home</h1>

    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for book in books %}
        <div class="col">
            <div class="card shadow-lg"> <!-- Added 'shadow-lg' class for larger shadow -->
                <img src="{{ book.image_url }}" class="card-img-top"
                    alt="{{ book.title }}" style="max-height: 200px;">
                <div class="card-body">
                    <h5 class="card-title" style="font-size: 16px;">{{ book.title }}</h5>
                    <p class="card-text">
    <span class="text-brown fw-bold"  >Book Category:</span>
    <span style="color:red " >{{ book.category_name }}</span>
</p>


                </div>
                <div class="card-footer">
                    <a  href="{{book.show_url}}"  class="btn btn-primary btn-sm">Show</a>
                    <form action="{{ url_for('books.delete_book', id=book.id) }}" method="post" class="d-inline">
                        <input type="hidden" name="_method" value="DELETE">
                        <button   type="submit" class="btn btn-danger btn-sm">Delete</button>
                    </form>
                   <a href="{{ url_for('books.book_update', id=book.id) }}" class="btn btn-success btn-sm">Update</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/books/update.html
{% extends 'layouts/base.html' %}

{% block content %}
<h1>Update Book</h1>

<form action="{{ url_for('books.book_update', id=book.id) }}" method="post">
    <div class="mb-3">
        <label class="form-label">Title</label>
        <input type="text" name="title" class="form-control" value="{{ book.title }}">
    </div>
    <div class="mb-3">
        <label class="form-label">Image</label>
        <input type="text" name="image" class="form-control" value="{{ book.image }}">
    </div>

    <div class="mb-3">
        <label  class="form-label">Price</label>
        <input type="number" name="price" class="form-control">
      </div>
    
    
      <div class="mb-3">
        <label  class="form-label">no of pages</label>
        <input type="number" name="no_of_pages" class="form-control">
      </div>


    <button type="submit" class="btn btn-primary">Update</button>
</form>
{% endblock %}

templates/categories/createcategory.html
{% extends 'layouts/base.html' %}

{% block content %}
<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow-lg">
                <div class="card-header bg-dark text-white">
                    <h1 class="text-center">Add New category</h1>
                </div>
                <div class="card-body">
                    <form action="{{ url_for('categories.createcategory') }}" method="POST">
                        {{ form.csrf_token }}
                        <div class="mb-3">
                            {{form.name.label}}
                            {{form.name(class="form-control")}}
                        </div>
                        <div class="mb-3">
                            {{form.description.label}}
                            {{form.description(class="form-control")}}
                        </div>


                        <div class="text-center">
                            <button type="submit" class="btn btn-success">Submit</button>
                               <a href="{{ url_for('categories.index') }}" class="btn btn-danger">Cancel</a>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/categories/index.html
{% extends 'layouts/base.html' %}

{% block content %}
<div class="container">
    <h1 class="text-center mb-4" style="color: brown; font-size: 28px; font-weight: bold; text-transform: uppercase;">
        CATEGORIES </h1>

    <table class="table">
        <tr>
            <th>ID</th>
            <th>NAME</th>
            <th>DESCRIPTION</th>


        </tr>

        {% for category in categories %}

       <tr>
           <td> {{ category.id }} </td>
           <td>  {{ category.name }}  </td>
           <td> {{ category.description }} </td>
       </tr>

        {% endfor %}
    </table>
</div>
{% endblock %}

templates/error404.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>404 Error</title>
    <style>
        body {
            background-color: #f8f9fa; /* Light gray background */
            font-family: Arial, sans-serif;
        }

        .container {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh; /* Full viewport height */
        }

        .error-content {
            text-align: center;
        }

        .error-message {
            font-size: 24px;
            margin-top: 20px;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="error-content">
            <img src="{{ url_for('static', filename='errors/404ERR.gif') }}" alt="404" class="img-fluid">
            <p class="error-message">Oops! The page you're looking for cannot be found.</p>
        </div>
    </div>
</body>

</html>

templates/layouts/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{url_for('static', filename='bootstrap/bootstrap/css/bootstrap.css')}}">
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Books Store</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ url_for('books.books_index') }}">Books</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{url_for('books.create')}}" class="nav-link active">Add New Book</a>
                    </li>
                     <li class="nav-item">
                        <a href="{{url_for('books.createform')}}" class="nav-link active">Add New Book from validate form</a>
                    </li>
                     <li class="nav-item">
                        <a href="{{url_for('categories.createcategory')}}" class="nav-link active">Add New category</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    <script src="{{url_for('static', filename='bootstrap/bootstrap/js/bootstrap.js')}}"></script>

</body>

</html>

templates/macros_.html
{% macro listobjects(objects)  %}

{% for obj in objects %}
<li style="color:black; font-weight:bold; "> {{obj}}</li>
{% endfor %}

{% endmacro %}


{% macro render_field(field) %}
    <dt>{{ field.label }}</dt>
    <dd>
        {{ field }}
        {% if field.errors %}
            <ul class="text-danger">
                {% for error in field.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </dd>
{% endmacro %}